const nombre = document.getElementById("nombre")
const correo = document.getElementById("correo")
const contraseña = document.getElementById("contraseña")
const confirmar_contraseña = document.getElementById("confirmar_contraseña")
const correo_inicio = document.getElementById("correo_inicio")
const contraseña_inicio = document.getElementById("correo_inicio")
